### ISSUE TITLE
Ember 1.10

### ISSUE THREAD

**Issue by mk-conn** [billysbilling/ember-animated-outlet#58]
Any chance to get this running with the latest Ember version?

**Comment by sebastianseilund** [comment]
Sorry for late reply! I'm afraid we're nearing the end of the life of ember-animated-outlet. I would check out newer and better solution such as [Liquid Fire](http://ef4.github.io/liquid-fire/).

**Comment by paimpozhil** [comment]
HI @sebastianseilund  not sure this is the best place to ask , We are using your ember-animated-outlet however one of our clients want us to do some sort of realtime transition where when the swipe the finger the transition starts/progresses as long as we complete the swipe or if we swipe on opposite direction the transition would abort and stay at current page.. 

Is this kind of thing do-able with the ember's transition model or should we say its impossible

**Comment by sebastianseilund** [comment]
@paimpozhil I don't think ember-animated-outlet will help you here.

What you're describing is definitely possible. You could ask on http://discuss.emberjs.com/ if anyone else have solved this issue before.

Off the top of my head, I think you will need to think a little outside routes and transitions though. Make a list of all the items. Make a swipe gesture handler that moves the position of the list around. When it stops, you can trigger a `replaceRoute()` call to update the URL to the currently centered item.

**Comment by paimpozhil** [comment]
Hey Sebastin,

Thanks for the pointers I will try my luck there .:)

Much appreciated, Loved your billysbilling as well , hopefully you make it
internationalized product soon like support for Indian banks someday

On Fri, May 29, 2015 at 12:17 AM, Sebastian Seilund <
notifications@github.com> wrote:

> @paimpozhil https://github.com/paimpozhil I don't think
> ember-animated-outlet will help you here.
> 
> What you're describing is definitely possible. You could ask on
> http://discuss.emberjs.com/ if anyone else have solved this issue before.
> 
> Off the top of my head, I think you will need to think a little outside
> routes and transitions though. Make a list of all the items. Make a swipe
> gesture handler that moves the position of the list around. When it stops,
> you can trigger a replaceRoute() call to update the URL to the currently
> centered item.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/billysbilling/ember-animated-outlet/issues/58#issuecomment-106563911
> .

## 

Paim Pozhil

**Comment by sebastianseilund** [comment]
Thanks :). You should be able to use Billy in India. Let me know if you have any specific problems.
